# Generated by Django 5.0.6 on 2025-09-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('decription', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills e.g.[Python, Java..]')),
                ('required_experience', models.FloatField(blank=True, help_text='Years of experience required', null=True)),
                ('required_education', models.CharField(choices=[('none', 'None'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PHD')], default='bachelor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('none', 'None'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PHD')], max_length=50, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(blank=True, default=dict, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
